import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { auth } from "@/auth";
import Providers from "./providers";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();

  return (
    <Providers session={session}>
      <html lang="pt-br">
        <body className={inter.className}>
          <Toaster />
          {children}
        </body>
      </html>
    </Providers >
  );
}
