import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();

  return (

    <html lang="pt-br">
      <SessionProvider session={session} refetchOnWindowFocus={true}>
        <body className={inter.className}>

          {children}

        </body>
      </SessionProvider>
    </html>
  );
}
